### ISSUE TITLE
HRNet vs HarDNet?

### ISSUE THREAD

**Issue by InternetMaster1** [Luonic/semi-supervised_semantic_segmentation#5]
Which is SOTA for lightweight segmentation?

I am looking to implement high-quality semantic segmentation on a mobile device for accurate human segmentation for still images (i.e. non-realtime).

I have been researching a lot of lightweight architectures/backbones for this purpose (HardNet, MobileNetV2, MobileNetV2plus, ShelfNet, FasterSeg, BiseNetV2, SINet, PortraitNet, etc)

Could HRNetV2-W18-Small-v2 be considered SOTA for this task? It achieves mIOU of 76.2% on Cityscapes.

The mIOU of U-HarDNet-70 is 75.9% & it is at the top of paperswithcode SOTA list for real-time segmentation.

You have implemented both in your library. What are your thoughts?

**Comment by Luonic** [comment]
@InternetMaster1 sorry for late reply :)
Hardnet in this repo is taker from official hardnet repo
For my case of skin segmentation on photos i got best result with hrnet-w48 that have been modified to be 0.5x deep
I pretrained with COCO Person class only
I did not really tested hardnet but hardnet's idea of using always 3x3 convolutions in used in stage 2,3 and 4 of hrnet
I can not understand motivation of hrnet authors to use bottleneck block for stage 1 because it gets pretty memory bandwidth intensive and occupies a lot of ram. I believe it is a resnet legacy in some way. 
For your case i would go with HRNetV2-w48 and if you have enough data then finetune it and then distill to w18
